Update FusionOne metrics workflow

diff --git a/.github/workflows/fusionone-post-metrics.yml b/.github/workflows/fusionone-post-metrics.yml
--- a/.github/workflows/fusionone-post-metrics.yml
+++ b/.github/workflows/fusionone-post-metrics.yml
@@ -65,6 +65,12 @@ jobs:
         env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
+      - name: Fail if installation ID is empty
+        if: steps.get_installation_id.outputs.id == ''
+        run: |
+          echo "Error: installation_id is empty. Workflow cannot continue."
+          exit 1
+
       - name: Post CheckmarxOne metrics to FusionOne
         if: steps.detect-type.outputs.result == 'cxone'
         uses: actions/github-script@v6
